version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bhim
      POSTGRES_USER: bhim
      POSTGRES_PASSWORD: Bhim@2001
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
